name: collectioneer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.2+1
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  icons_launcher: ^2.1.7
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
